# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKOybzKV0L_i7p3scXk-e9FCwxjx9H4I
"""

# Import necessary libraries
import pandas as pd
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('/content/creditcard.csv')

# Preprocessing the data (drop 'Class' column for unsupervised learning)
X = df.drop('Class', axis=1)

# Initialize the Isolation Forest model
model = IsolationForest(n_estimators=100, contamination=0.01, random_state=42)

# Fit the model to the data
model.fit(X)

# Predict anomalies (1: normal, -1: anomaly)
df['Anomaly'] = model.predict(X)

# Visualize the detected anomalies
plt.scatter(df['V1'], df['V2'], c=df['Anomaly'], cmap='coolwarm')
plt.title('Anomaly Detection using Isolation Forest')
plt.xlabel('Feature V1')
plt.ylabel('Feature V2')
plt.show()

# Show number of anomalies detected
print(f"Anomalies detected: {df['Anomaly'].value_counts()}")